language: node_js
node_js:
    - 10
before_install:
    - npm install -g codecov
install:
    - npm ci
    - cd ./packages/kpc-angular && npm ci
addons:
    chrome: stable
before_script:
    - npx gulp doc
    - npm run build:angular
script:
    - npm run test
    - codecov
    - npm run test:react
    - npm run test:angular
